import Head from 'next/head'
import { Container, Card, Row, Text } from '@nextui-org/react'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />      
        <Container>
          <Card color="secondary">
            <Row justify="center" align="center">
              <Text h6 size={15} color="white" css={{ m: 0 }}>
                NextUI gives you the best developer experience with all the features
                you need for building beautiful and modern websites and
                applications.
              </Text>
            </Row>
          </Card>
        </Container>
      </main>
    </div>
  )
}
